Repository cslant/blog-core, pull requests merged in 2024-07, with the labels that each got.

#10 Feature/first generate core package #1
  .gitignore
  .scrutinizer.yml
  .styleci.yml
  common/helpers.php
  composer.json
  config/blog-core.php
  lang/en/blog-core.php
  phpstan-baseline.neon
  phpstan.neon.dist
  phpunit.xml
  routes/blog-core.php
  src/Providers/BlogApiServiceProvider.php
  tests/IntegrationTest.php
Labels: enhancement

#13 feat: change text api to core #1
  composer.json
  config/blog-core.php
  phpunit.xml
  routes/blog-core.php
Labels: enhancement

#15 feat: add commit rule sample for Core package #3
  .github/commit_message.txt
  README.md
Labels: enhancement, feature request

#16 feat: add pull request rule sample for core package repo #4
  .github/pull_request_template.md
Labels: enhancement, feature request

#17 feat: setup workflow to test code style #2
  workflows/phpstan.yml
Labels: enhancement, feature request

#18 feat: create a workflow to test the composer running #5
  .github/workflows/setup_test.yml
Labels: enhancement, feature request

#12 install scout and elastic packages #7
  composer.json
  phpstan-baseline.neon
  src/Http/Controllers/Base/BaseCategoryController.php
  src/Http/Controllers/Base/BasePostController.php
  src/Http/Controllers/Base/BaseTagController.php
  src/Models/Traits/IsIncrementing.php
Labels: enhancement, feature request

#21 updated docs and removed unnecessary lines
  routes/blog-core.php
Labels: proposal

#22 Feature/handle first elasticsearch config #19
  composer.json
  config/blog-core.php
  src/Commands/ListProviders.php
  src/Providers/BlogCoreServiceProvider.php
  src/Providers/ElasticSearchServiceProvider.php
Labels: enhancement, feature request

#24 #19 feat: create register config method to register all config file i…
  .github/workflows/phpstan.yml
  .github/workflows/setup_test.yml
  composer.json
  config/elasticsearch.php
  config/scout.php
  src/Providers/BlogCoreServiceProvider.php
Labels: enhancement, feature request
