Repository cslant/blog-core, pull requests merged in 2025-03, with the labels that each got.

#36 Fix/analyse dependent
  config/l5-swagger.php
  src/Models/Page.php
Labels: documentation, dependencies

#37 Fix styling
  phpstan-baseline.neon
  src/Models/Category.php
  src/Models/MetaBox.php
  src/Models/Page.php
  src/Models/Post.php
  src/Models/Role.php
  src/Models/Slug.php
  src/Models/Tag.php
  src/Models/User.php
Labels: bug

#38 fix: update property for post
  src/Models/Post.php
Labels: bug

#39 #64 fix: add action for core
  phpstan-baseline.neon
  src/Http/Actions/Action.php
Labels: bug, dependencies

#42 #28 feat: add property posts_count
  src/Models/User.php
Labels: feature request

#43 Feature/add property user
  src/Models/User.php
Labels: feature request

#45 feat: add relationship with count post
  src/Models/Category.php
  src/Models/Tag.php
Labels: feature request

#44 Feat/config expieration view time env
  config/blog-core.php
Labels: dependencies
